### ISSUE TITLE
Excuse themselves from vote (2)

### ISSUE THREAD

**Issue by yannjoly** [ga4gh/product-process#19]
Same issue on 20 c.  as I flagged under 12 II c. This behavior should not be encouraged.

**Comment by fabiolib** [comment]
I agree. The ability to nominate a proxy should cover occasions where members feel they are unable to assess appropriately or remain unbiased in their voting.

**Comment by susanfairley** [comment]
@fabiolib - confused on if you are agreeing with @yannjoly that abstention should be discouraged (the previous comment) or if you support abstention where people feel they have inadequate knowledge (which Yann, I think, opposes)? Could you clarify your position. Thanks.

**Comment by fabiolib** [comment]
Sorry for the confusion, I missed Yann's previous comment. I agree that ruling oneself out because you feel you have insufficient technical understating should be discouraged, but not prevented. However, voter abstention, especially in small groups, can skew outcomes, so I think encouraging (if not forcing) the voter to choose a proxy still gives them some power to influence the final result. I hope this is clearer.

**Comment by susanfairley** [comment]
Thanks @fabiolib  - that sounds like in favour of proxies (so that people can have someone on their project with greater knowledge handle it) but reluctant to see people abstain without a proxy replacing their vote. Appreciate the clarification - thanks again.
