### ISSUE TITLE
Percentage votes to gate progress

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh/product-process#6]
Step 13 talks about a situation where a tied vote could be sufficient to push a study group through for further standards development. I worry that a tied vote is indicative of something much deeper and wonder what situation would permit this standard to succeed at stage 21. I feel that there should be a much stronger vote towards approval at step 13 e.g. 60%. In addition if something was to fail at that point I don't see what mechanism there is for feedback. Personally I wouldn't like a study group to be rejected for apparently no reason or feedback given.

**Comment by susanfairley** [comment]
Thanks for the feedback @andrewyatz.

I think this is a tricky balancing act - like you I would hope to see a proposal getting stronger support at step 13 but we also (I think) want to recognise that there could be good ideas that maybe not everyone supports initially, so I'd hesitate to set the bar too high here (although interested to hear opinions on this one). 

For the SC presentation at step 13, I'd be hoping that this served as a) a check that the Study Group outputs make some sense to a broader group (there should have been detailed feedback already from the PRC) and b) an opportunity to inform SC about the work and engage Driver Projects and others who may not have already become involved.

I think in an earlier iteration a 'No' from SC bounced back to further review by the group (as happens at some other stages in the process) but we also need to draw the line somewhere. If we were to increase the SC voting bar here, so that it was harder to pass, I'd certainly be interested in giving the group a chance to review and get feedback. As the bar is currently relatively low, I'm possibly more comfortable saying that, if that hasn't been met, it's time to stop.

Very interested in further comments on this.

**Comment by andrewyatz** [comment]
I think my comments on this are split between this issue and #2 but my feeling here was more whatever SC are meant to be approving, they do so with a clearer voting majority (I personally would exclude non-voters from the percentages). Nearly to act in bands of approval suggesting clear support/middling support/no support as each of these bounces back from SC will affect the SG differently. But again we need to be clear on what SC are voting on.

**Comment by susanfairley** [comment]
I feel I have heard a mix of opinions on voting. However, my feeling is that, I'm hearing more support for enabling SC members to step back from content votes (while allowing delegation and also requiring a minimum number of votes).

The process is set up to require consultation and feedback *before* products go to SC, so I have some sympathy for the feedback point but feel that, if work has gone well, there ought not to be new information coming to light.

That said, it could be possible to modify our voting setup (a Google form) to ask that when people vote against, they give a reason. This relates to #13 too.

**Comment by susanfairley** [comment]
OK, not sure if these changes make it easier or harder to get approval but...

I have raised the bar to require 60% of casts votes in favour and at least 50% of votes must be cast at all SC votes (12, 20 and 22).

Following the study group/phase, if work is rejected, it bounces back to the group (13->9). They can consider next steps but two rejections at the same stage are taken to indicate that work should stop (but this can be appealed to exec). Similar wording is added at 19 if work is rejected twice at the final stages.

Link to the commit is above.
