### ISSUE TITLE
Demonstrated need for standard by external study groups

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/product-process#7]
In issue #2, there was a comment about the challenges of creating study groups, when we are already hard-pressed to get people to develop these specifications. While I believe everyone agrees in principle with the notion that standard development needs to occur with broad community needs in mind, convening a set of experts (beyond those already participating in the GA4GH Work Streams) for any proposed standard development may be overly burdensome to the process. In some cases the needs are largely technical and best addressed by the existing specification maintainers (speaking to the issues raised by @jkbonfield in #2), in other cases there have been large efforts that have already identified needs that could be better represented with a report than creating an _ad hoc_ study group.

For example, in VICC we are currently working with a large clinical community (representatives from CAP, ACMG, CGC, ClinGen, and VICC) to define the minimal data elements for Gene Fusions–an effort that has taken years to build consensus guidelines, which I expect will ultimately inform the development of a corresponding data exchange model in VRS. The development of that model will then have benefited from a clinical community to drive the data requirements, and a data modeling community (the GKS VR team) to develop the nuts and bolts for the standard. It is unclear how a study group effectively complements this expertise.

Is there any way that existing efforts to build community consensus (such as the above cross-consortia study) can be used as a proposal in lieu of a new _ad hoc_ study group? Perhaps reviewed and approved by Work Stream leads prior to further development work? And leave study group formation as an option to be exercised by those leads if they feel the groundwork for the proposal is insufficient / additional expertise is required?

**Comment by arendon** [comment]
I think an important part of the argument is what is the purpose and the strategy of GA4GH: do we build standards for the sake of it, or do we aim to enable genomics and health globally through standards. The reason is that if it is the latter, then a stronger product mindset is required to ensure that the standards will indeed deliver on that aim. So, very much along the lines of what has been set above:

**Product Market Fit**: Is this a thing that people would like to use to sort out a major obstacle/use case? Is it such an obstacle/use case important enough that it will encourage the adoption of the standard instead of either building in isolation or not fulfilling the specific need? Are use cases and vision of how users would adopt compelling?

**Can We Build It**: Do we have the technical competency to design a standard in this area? What is the relationship between the standard and other technologies (for example to work at the scale envisioned)? Is the standard going to be so complicated that it will not going to be adopted [reliably]?

**Can We Afford Building It / Can our stakeholders support this**: Somewhat less clear in this context but something around priorities of the standard versus better use of time, or likely endorsement by the community.

I definitely would like to see some answers to these questions when reviewing a standard as an steering committee member and not simply trust the workstream or indeed the product review committee.

**Comment by susanfairley** [comment]
Thanks @arendon for adding to this. These are interesting points. 

My understanding is that, no, our philosophy has not been standards for the sake of it. Instead, few standards or broad use.

If I have understood the direction of your comments, you are looking to see review of the feasibility of a given product (compelling use case, technical capability, good use of time, etc) to assist in gauging if a product merits further exploration?

Interested in further feedback here.

Also flagging further conversation on minor updates on #2

**Comment by susanfairley** [comment]
I have made some edits to the process reflecting this conversation.

1. I have made changes with the aim of clarifying expectations around a study group or phase interacting with existing efforts in the space and adding that pointing to existing work in the space is fine (but that breadth of representation should be a consideration)
2. I have added a criteria that the likely viability of the product should be considered.

These sit alongside changes made on issue #2 relating to urgent fixes, continued development and making it clearer that the study stage can be the same people but with an explicit focus on scoping work and defining the problem being addressed.

I hope these improve the overall document.
