### ISSUE TITLE
Planning for adoption as part of the standard development process

### ISSUE THREAD

**Issue by melissacline** [ga4gh/product-process#9]
The standard development process doesn't appear to show efforts for adoption of the standard, which technically aren't part of the development process yet are crucial for the standard to gain traction.  Some thing that help are:
- Adoption by major stakeholders
- Development of a reference implementation
The approaches that are impactful vary by the standard, and so there is no one-size-fits-all strategy.  For example, the BED standard was already widely adopted before it was added to the GA4GH standards portfolio, while adoption of VRS benefitted greatly from the production of a reference implementation.  Perhaps an expedient approach is for the PRC to consider adoption strategies as part of the standards development process, which could include gaining the buy-in of appropriate major stakeholders and/or planning for development of a reference implementation.

**Comment by vdauwera** [comment]
I read step 14 as an attempt to include efforts toward adoption, at least at the level of major stakeholders. Are you looking for something more broad than that? 

I was actually looking more at step 16 ("Open for comment") as a weak point -- might be worth explicitly committing comms support for circulating announcements etc. It can take a lot of work to reach a wide public community effectively.

**Comment by ajhpage** [comment]
the GA4GH comms team is working on a set of communications best practices to run alongside the product development process. eg., at step 16, when something is posted for open comment, this will lay out what activities comms will do and what we need from the dev team. Or, when a new study group is convened, we will have a set of recommended best practices for how to share that with the community and invite participation.

**Comment by susanfairley** [comment]
Thanks for these comments.

I think @melissacline makes a good point.

@vdauwera, you are correct that 14 is looking to address some of this (in terms of implementation) and earlier at 6 we are looking for lists of potential adopters, who we would want to be keeping in touch with. As @ajhpage mentions, there are plans to put together comms support plans.

I do wonder, however, if it might make sense to also look at developing a road map for adoption for each standard. For clarity, the standards should always be adopted (or not) freely and based on utility - we should not be "pushing" people to adopt our standards just because. However, given that the standard is an appropriate choice for someone, I do think we should be doing what we can to make it as easy as possible, for those who wish to, to be able to adopt the standard.

I think that @melissacline is correct that the landscape here will vary from product to product. The work required at the study phase of work should have provided information relevant to thinking about what blocks might exist for adoption of a given standard and how those might be addressed. Examples that come to mind for me could include: improved documentation, reference implementation, test/compliance infrastructure, supporting adoption by key groups, follow up studies demonstrating utility, etc, etc.

Happy to hear thoughts on the "approval to adoption" roadmap idea.

Also noting the discussion on implementations taking place on #24

**Comment by andrewyatz** [comment]
I think a roadmap to adoption is a good idea. At least some bullet points to say where would a standard look to push towards to drive adoption.

**Comment by susanfairley** [comment]
I have added in the roadmap. The changes are under points 14 and 17, adding the roadmap to the outputs of the development group and adding it to the review criteria. Link to the relevant commit is above. I also noticed that the term 'standard' was being used instead of 'product' in some places and have edited accordingly.
